### ISSUE TITLE
[Bug] DPK-connector should save files with correct mime type extension

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#780] opened 2024-11-06 07:44 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

I am downloading HTML files from base url : https://thealliance.ai/our-work

the saved files are missing '.html' extension.

### Reproduction script

https://github.com/sujee/data-prep-kit/blob/html-processing-1/examples/notebooks/html-processing/1_download_site.ipynb

### Anything else

data_prep_connector          0.2.2

### OS

Ubuntu

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sujee** [comment] 2024-11-06 07:46
CC : @Qiragg

**Comment by hmtbr** [comment] 2024-11-06 09:10
@sujee It's not a bug but working as expected. Your code tries to extract the filename and extension from the url string. It won't get `.html` if the url doesn't include it.

**Comment by Qiragg** [comment] 2024-11-06 20:47
@sujee If you want to include html extension if it is not specified in the url, you can do the following:

1. Extract mime_type
2. Use mime_type to assign an extension if an extension already cannot be extracted from the url
3. Save file with the right extension

We have not used this logic extensively in practice as we are used to saving files without the html extension if we cannot parse it from the url.

@touma-I @hmtbr the only question is should we provide support for such functions in the dpk_connector utils or should they remain in utils supporting the notebooks that are designed for the specific use case.

**Comment by Qiragg** [comment] 2024-11-06 20:54
In hindsight, it might not be a bad idea to provide utils function in the dpk_connector that allow local storage for ease of use for the end-user. Although these functions are simply enough to write, I would like to remove dev time it takes for any user to get this up and running.

**Comment by sujee** [comment] 2024-11-06 21:13
@Qiragg first off, thanks for all the explanations and helpful hints.  I very much appreciate it.

I would absolutely recommend, we provide some utilities / wrapper functions to perform some of the most common tasks in crawling and saving data.  Otherwise  its just too much work left for the user.  I might as well use plain Scrapy :smile: 

I am going to go through the full crawl process, so I can fully understand what is supplied by DPK-connector-core and what's left for user.  And I will come back with recommendations and suggestions.  And we can have a discussion to see what makes sense.

**Comment by Qiragg** [comment] 2024-11-06 21:57
@sujee thanks, please do let us know what are the functions we will need to run some of the most common tasks that we can incorporate inside the utils. We definitely want to make it very easy for the user to spin-up a notebook and get the end result they need without needing to know how to code.

**Comment by touma-I** [comment] 2024-11-08 14:38
@sujee I am closing this issue as most of this should be handle by the transform. I suggest, you wait until the transform is in place so you can provide direct comments on how it can be improved.

**Comment by touma-I** [comment] 2024-11-08 14:41
@Bytes-Explorer There is already an issue for the transform. Not convince adding this issue to the grow@DPK makes sense. Once the first iteration transform is in place, we can run some evaluation and create new issues for enhancement.

**Comment by touma-I** [comment] 2024-11-08 14:43
The current design calls for a transform to do what is in here.

**Closed as completed by touma-I** 2024-11-08 14:43 UTC
Labels: bug
