### ISSUE TITLE
[Bug] possible regression on ededupe code in release dev3

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#585] opened 2024-09-11 22:20 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/universal/tokenization

## In dev1 release (expected behavior)

 https://github.com/sujee/data-prep-kit/blob/rag-example1/examples/notebooks/rag/rag_1A_dpk_process_ray.ipynb

### Step-3: Chunking 

output

```text
Files processed : 3
Chunks created : 2,042
Input data dimensions (rows x columns)=  (3, 12)
Output data dimensions (rows x columns)=  (2042, 15)
```

###  Step-4 : EDedupe

Output

```text
Input data dimensions (rows x columns)=  (2042, 15)
Output data dimensions (rows x columns)=  (1324, 15)
Input chunks before exact dedupe : 2,042
Output chunks after exact dedupe : 1,324
Duplicate chunks removed :   718
```

## In Dev-3 (incorrect behavior)

https://github.com/sujee/data-prep-kit/blob/rag-example1-dev/examples/notebooks/rag/rag_1A_dpk_process_ray.ipynb

### Step-3: Chunking 

output

```text
Files processed : 3
Chunks created : 1,973
Input data dimensions (rows x columns)=  (3, 12)
Output data dimensions (rows x columns)=  (1973, 15)
```

### Step-4: EDedupe

output

```text
Input data dimensions (rows x columns)=  (1973, 15)
Output data dimensions (rows x columns)=  (2, 16)
Input chunks before exact dedupe : 1,973
Output chunks after exact dedupe : 2
Duplicate chunks removed :   1971
```

**Note: how resulting number of chunks is only 2**

This is the problem.

The result is not chunks but the documents!

This in turn breaks vector search and RAG responses.

### Reproduction script

dev1 (expected behavior) : https://github.com/sujee/data-prep-kit/blob/rag-example1/examples/notebooks/rag/rag_1A_dpk_process_ray.ipynb

dev3 (incorrect behavior) : https://github.com/sujee/data-prep-kit/blob/rag-example1-dev/examples/notebooks/rag/rag_1A_dpk_process_ray.ipynb

### OS

Ubuntu

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment] 2024-09-12 17:31
@sujee can you reproduce this problem in ededup w/o first running the chunker.  That is, ededup all by itself.  The chunker does seem to produce different results in the two cases above, so is that somehow the real problem?

**Comment by sujee** [comment] 2024-09-13 15:20
another example working on simpler PDFs is here : https://github.com/sujee/data-prep-kit-examples/blob/main/dpk-intro/dpk_intro_1_python.ipynb

**Comment by dolfim-ibm** [comment] 2024-09-18 08:36
After reviewing with @blublinsky we found out that
- what you observe is because `ededupe` is using the `doc_id` column as a first criteria
- the `doc_chunk` transform is keeping the source `doc_id`, i.e. all chunks belonging to the same source document will have the same `doc_id`

We have two solutions
1. In the current notebook, after `doc_chunk` we could run the `doc_id` transform pointing it to a different column, i.e. `hash_column="chunk_id"`, then `ededupe` can be configured with `doc_id_column="chunk_id"`.
2. We update the `doc_chunk` transform such that it renames `doc_id` to `source_doc_id`. This way the `doc_id` can still be used as a "row identifier".

If nobody objects, we can go with both solutions. 1) should easily unlock you, 2) will also make sure we don't fall in the same trap in the future.

**Comment by blublinsky** [comment] 2024-09-18 09:41
I still think that the second solution is a better option. From user's point of view Doc_id is a row identifier and I will preffere to keep it this way to avoid confusion in the future

**Comment by daw3rd** [comment] 2024-09-18 12:35
this seems like it could be a problem from any transform that does splitting of rows.  Would another solution be to run the doc_id transform just prior to ededup and make this a general recommendation when using e/fdedup?

**Comment by blublinsky** [comment] 2024-09-18 12:48
For me the bigger issue was that doc-id column was misleading

**Comment by sujee** [comment] 2024-09-18 15:17
@dolfim-ibm @blublinsky  thanks for investigating.

Is (1) I can do within my notebook 100% ?  If so, I will try that, while we put in a long term solution (2).

If I can get some sample code for (1) that would be very helpful.  thx

> We have two solutions
> 
> 1. In the current notebook, after `doc_chunk` we could run the `doc_id` transform pointing it to a different column, i.e. `hash_column="chunk_id"`, then `ededupe` can be configured with `doc_id_column="chunk_id"`.
> 2. We update the `doc_chunk` transform such that it renames `doc_id` to `source_doc_id`. This way the `doc_id` can still be used as a "row identifier".
> 
> If nobody objects, we can go with both solutions. 1) should easily unlock you, 2) will also make sure we don't fall in the same trap in the future.

**Comment by sujee** [comment] 2024-09-19 05:22
I was able to use method (1) get ededupe work as expected.  Thanks every one! :-)

**Comment by blublinsky** [comment] 2024-09-19 07:26
Great.
Thanks @dolfim-ibm for fixing this so quickly
Can we, please, close this one.

**Closed as completed** 2024-09-25 20:53 UTC
Labels: bug, fixed
