### ISSUE TITLE
[Feature]  In-Memory / no persistence storage runtime

### ISSUE THREAD

**Issue by touma-I** [data-prep-kit/data-prep-kit#544] opened 2024-08-26 15:45 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Library/core

### Feature

In certain environment there is a need not to rely on persistence storage (local disk, S3, etc.). Currently, when a transform is initialized, it defines the folders where the input and output for the transform reside. It would be desirable to identify an alternative approach where the referenced input/output are in-memory objects.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by touma-I** [comment] 2024-08-26 15:47
@touma-I to investigate how this is currently done by the datasift team.

**Comment by daw3rd** [comment] 2024-08-26 23:02
Isn't this a call to transform() with an arrow Table or transform_binary() with byte array and file name (dummy perhaps) that indicates the file extension?  If not, can you suggest an API?

**Comment by daw3rd** [comment] 2024-09-13 16:25
This may be satisfied with the in-memory transform pipeline PR #424

**Comment by daw3rd** [comment] 2024-09-13 16:34
This may be duplicate of issue #374

**Comment by daw3rd** [comment] 2024-09-16 16:25
Closing and moving design discussion to #374

**Closed as completed by daw3rd** 2024-09-16 16:25 UTC
Labels: duplicate, enhancement
