### ISSUE TITLE
Ray error during noop pipeline run - local KFP and Kind

### ISSUE THREAD

**Issue by ykoyfman** [data-prep-kit/data-prep-kit#27] opened 2024-04-29 19:55 UTC
Environment: KFP + Kind on Mac M1 Max with Docker and Colima. VM settings:   `default    Running    aarch64    8CPU       32GiB     1000GiB    docker`

During `noop` pipeline execution (all default values), execute ray step fails with:

<img width="1472" alt="image" src="https://github.com/IBM/data-prep-lab/assets/13653608/5bc31a06-5158-4fbf-b00a-deb09c907ad6">

**Comment by roytman** [comment] 2024-04-30 20:27
tried to reproduce it on Mac M1 with Podman VM settings: 9 CPUs, 67 GB RAM
<img width="1459" alt="image" src="https://github.com/IBM/data-prep-lab/assets/1816654/a5c484c7-d591-4d76-85c4-419456aa65a2">

**Comment by roytman** [comment] 2024-05-01 04:31
@Mohammad-nassar10 , can you try the test on your Intel-based laptop?

**Comment by Mohammad-nassar10** [comment] 2024-05-01 05:58
I tried it with the default values that exist in the workflow and it passed and generated output file.
![image](https://github.com/IBM/data-prep-lab/assets/79787844/90c9076a-3dbd-443f-bc9b-7edbeb2652ac)

**Comment by roytman** [comment] 2024-05-01 06:05
I have faced the issue when [podman inspect or stop return "json: cannot unmarshal array into Go struct field InspectContainerConfig.Config.Entrypoint of type string](https://github.com/containers/podman/discussions/22531).  We have observed it with Hajar. 
Therefore, I updated Podman to the latest version v5.0.2; it started successfully, but the Ray execution failed again with a different error
<img width="1589" alt="image" src="https://github.com/IBM/data-prep-lab/assets/1816654/a6c69ee3-fcb8-4072-931d-8a4a73f919e2">

We decided we don't support Mac with Apple silicon, didn't we?

**Comment by blublinsky** [comment] 2024-05-01 08:23
Works for me as well. Just re tested

<img width="1485" alt="Screenshot 2024-05-01 at 9 04 14 AM" src="https://github.com/IBM/data-prep-lab/assets/25286171/14f6eb10-0bc7-4f33-b30e-e3e9bffb37f1">
<img width="1700" alt="Screenshot 2024-05-01 at 9 05 26 AM" src="https://github.com/IBM/data-prep-lab/assets/25286171/b2efd59e-85f6-407c-a83f-686588e55693">

**Comment by blublinsky** [comment] 2024-05-01 08:24
Will try to work with Alexey later today to try it on his Mac

**Comment by roytman** [comment] 2024-05-01 08:38
Restarted my laptop and tried it again with Podman.

It showed success, but we can see errors in the logs.
<img width="1449" alt="image" src="https://github.com/IBM/data-prep-lab/assets/1816654/6ec93f59-53a5-4392-8a3b-550e212712ba">
And actually, it submitted two jobs: one Failed, and another is Running for ever.

<img width="1658" alt="image" src="https://github.com/IBM/data-prep-lab/assets/1816654/d96a2e2e-03e2-4ad8-a156-44dcfcafde55">

**Comment by blublinsky** [comment] 2024-05-01 10:05
So I think the bottom line is that M1 with Podman is not a supported version for this release.

**Comment by blublinsky** [comment] 2024-05-02 14:13
@roytman, @ykoyfman, @shahrokhDaijavad I think we can close this one

**Comment by shahrokhDaijavad** [comment] 2024-05-02 18:54
@blublinsky I am ok with saying that a Mac M1 with Podman is not supported for kfp in this release, but of course it is ok for individual transforms and using S3-compatible Object Store locally. However, I want to make sure we get confirmation from @ykoyfman that he was able to run a full kfp test on a virtual X86 environment, before closing it.

**Comment by ykoyfman** [comment] 2024-05-02 20:49
@shahrokhDaijavad - Agree - I'm continuing to test on X86 VM.   Initially created a 32GB/8xCPU/100GB RHEL9 VM - Kubeflow could not completely start under Kind on this VM.

**Comment by blublinsky** [comment] 2024-05-03 08:26
do not use RHEL9, use Ubuntu

**Comment by roytman** [comment] 2024-05-03 16:53
Please do not close the issue, given that we have more time, I want to try to resolve the M1 limitations.

**Comment by shahrokhDaijavad** [comment] 2024-05-03 17:16
Sure, Alexey.

**Comment by blublinsky** [comment] 2024-05-14 07:22
@roytman, @ykoyfman, @shahrokhDaijavad. I think we tested this to death and have most of the answers. Can we, please, close it

**Comment by roytman** [comment] 2024-05-14 09:34
no, as we discussed it still doesn't work on Mac M1. Somehow we should resolve it.

**Comment by shahrokhDaijavad** [comment] 2024-05-14 19:03
@blublinsky: As you have seen in the tech slack channel, @ykoyfman is running this today on a RHEL VM. Once he is successful, we can close this, other than the Mac M1 problem that @roytman points to and may not have a short-term solution.

**Comment by shahrokhDaijavad** [comment] 2024-05-17 15:45
Success by @ykoyfman today in running noop with kfp on RHEL VM! I close this issue for now, because I think Mac M1 may not be short-term.

**Closed as completed by shahrokhDaijavad** 2024-05-17 15:45 UTC
Labels: bug, fixed
