### ISSUE TITLE
[Bug] chunking fails on PDFs with one line text

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#590] opened 2024-09-14 07:10 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### What happened + What you expected to happen

I am trying process very simple PDFs.  Each PDF has one line. See attached example.

When I supply 2 PDFs, I expect 2 chunks as output.  But I get zero chunks as output.

[a1.pdf](https://github.com/user-attachments/files/17001397/a1.pdf)
[b1.pdf](https://github.com/user-attachments/files/17001398/b1.pdf)

### Reproduction script

data and code are here : https://github.com/sujee/data-prep-kit/tree/test-ededupe/test/test-ededupe

### OS

Ubuntu

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dolfim-ibm** [comment] 2024-09-16 06:14
In those documents, the text is detected as Page-footer, which are ignored in the markdown export and chunking.

I don't think we want to change the chunker or exporter for to include footers. This might be resolved with a new layout model, but we don't have yet an eta for it.

**Comment by sujee** [comment] 2024-09-16 06:36
I am on dev3 release, here is the output for input file a1.pdf.

Does this track with your observation?

```json
{"_name": "",
 "description": {"logs": []},
 "equations": [],
 "figures": [],
 "file-info": {"#-pages": 1,
               "document-hash": "4512df83786d672e062f144a718290982e3a8952c20ddb11014cbb3dcb9b507d",
               "filename": "a1.pdf",
               "page-hashes": [{"hash": "1a75ddf16ddb235368915aed32ab00ccd753838488ec3bb785be9bb84c0d9259",
                                "model": "default",
                                "page": 1}]},
 "footnotes": [],
 "main-text": [{"name": "Text",
                "prov": [{"bbox": [132.78564453,
                                   655.18377686,
                                   251.93409729,
                                   665.57006836],
                          "page": 1,
                          "span": [0, 29]}],
                "text": "Twinkle, twinkle, little star",
                "type": "paragraph"},
               {"name": "Page-footer",
                "prov": [{"bbox": [303.13299561,
                                   87.43224335,
                                   308.11428833,
                                   96.62137604],
                          "page": 1,
                          "span": [0, 1]}],
                "text": "1",
                "type": "page-footer"}],
 "page-dimensions": [{"height": 792.0, "page": 1, "width": 612.0}],
 "page-footers": [],
 "page-headers": [],
 "tables": [],
 "type": "pdf-document"}
```

**Comment by dolfim-ibm** [comment] 2024-09-16 06:43
Oh right, the footer was actually the page number. This is indeed interesting. We will evaluate it more.

**Comment by dolfim-ibm** [comment] 2024-09-16 08:36
The issue is actually related the text length. The chunker has a parameter for it with default value `min_chunk_len=64`.

In the new version of the library we actually expose it as a parameter, I think we could easily propagate it as an argument for the DPK transform as well.

**Comment by dolfim-ibm** [comment] 2024-09-16 09:20
The PR https://github.com/IBM/data-prep-kit/pull/591 will add the option to customize the minimum value.

**Comment by sujee** [comment] 2024-09-16 18:59
> The PR #591 will add the option to customize the minimum value.

very nice 👏

**Closed as completed** 2024-09-20 08:30 UTC
Labels: bug
